# This file was generated by the {rix} R package v0.17.2 on 2025-12-13
# with following call:
# >rix(r_ver = "4.4.2",
#  > r_pkgs = r_pkgs,
#  > system_pkgs = system_pkgs,
#  > ide = "none",
#  > project_path = pkg_path,
#  > overwrite = TRUE,
#  > print = TRUE)
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-02-24.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      curl
      devtools
      dplyr
      httr2
      janitor
      jsonlite
      languageserver
      lintr
      lubridate
      pkgdown
      purrr
      quantmod
      readr
      readxl
      rvest
      stringr
      tarchetypes
      targets
      testthat
      tibble
      tidyquant
      tidyr
      usethis
      xml2;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      git
      glibcLocales
      nix
      pandoc
      quarto
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
