# package.nix - Builds etfdata as a Nix derivation from local source
# Generated by: R/setup/generate_nix_files.R

{ pkgs ? import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-12-22.tar.gz") {} }:

pkgs.rPackages.buildRPackage rec {
  name = "etfdata";
  version = "0.0.0.9000";
  src = ./.;

  propagatedBuildInputs = with pkgs.rPackages; [
    dplyr
    httr2
    janitor
    jsonlite
    logger
    lubridate
    magrittr
    purrr
    quantmod
    readr
    rlang
    rvest
    stringr
    tibble
    utf8
  ];

  nativeBuildInputs = with pkgs.rPackages; [
    knitr
    rmarkdown
    quarto
  ];

  doCheck = false;

  meta = with pkgs.lib; {
    description = "European UCITS ETF Data Collection";
    license = licenses.mit;
  };
}

