# Session Log: Cleanup Package
# Date: 2025-12-12
# Issue: #9

library(desc)
library(usethis)

pkg_path <- "finance/data/etfs/etfdata"
desc_path <- file.path(pkg_path, "DESCRIPTION")

# 1. Update DESCRIPTION
d <- description$new(desc_path)
d$set_dep("knitr", "Suggests")
d$set_dep("rmarkdown", "Suggests")
d$set("VignetteBuilder", "knitr")
d$write(desc_path)

# 2. Update .Rbuildignore
# We need to ignore targets infrastructure and local libs
ignores <- c(
  "^_targets$", 
  "^_targets.R$", 
  "^local_lib$",
  "^common.R$"
)
for (ig in ignores) {
  # Append if not exists (simple append for now)
  write(ig, file = file.path(pkg_path, ".Rbuildignore"), append = TRUE)
}

# 3. Create globals.R to fix NSE warnings
globals_content <- "
# Generated by 09_cleanup_package.R
utils::globalVariables(c(
  \"Open\", \"High\", \"Low\", \"Close\", \"Volume\", \"Adjusted\", \"date\"
))
"
writeLines(globals_content, file.path(pkg_path, "R/globals.R"))

message("Package cleanup complete. Manual editing of R files needed for imports.")