# Generate package.nix for etfdata
# Usage: Rscript R/setup/generate_nix_files.R

desc <- read.dcf("DESCRIPTION", all = TRUE)
desc <- as.list(desc[1, ])

get_field <- function(name) {
  value <- desc[[name]]
  if (is.null(value) || is.na(value) || !nzchar(value)) {
    return("")
  }
  value
}

parse_deps <- function(field) {
  raw <- get_field(field)
  if (!nzchar(raw)) {
    return(character(0))
  }
  parts <- unlist(strsplit(raw, ",", fixed = TRUE))
  parts <- gsub("\\(.*?\\)", "", parts)
  parts <- trimws(parts)
  parts[nzchar(parts)]
}

normalize_nix_name <- function(pkg) {
  if (pkg == "data.table") {
    return("data_table")
  }
  pkg
}

escape_nix_string <- function(text) {
  text <- gsub("\\\\", "\\\\\\\\", text)
  gsub("\"", "\\\\\"", text)
}

imports <- parse_deps("Imports")
depends <- setdiff(parse_deps("Depends"), "R")
suggests <- parse_deps("Suggests")
vignette_pkgs <- intersect(suggests, c("knitr", "rmarkdown", "quarto"))

deps <- unique(c(imports, depends))
deps <- vapply(deps, normalize_nix_name, character(1))
vignette_pkgs <- vapply(vignette_pkgs, normalize_nix_name, character(1))

format_nix_list <- function(pkgs) {
  if (length(pkgs) == 0) {
    return("    # (none)")
  }
  paste(sprintf("    %s", pkgs), collapse = "\n")
}

pkg_name <- get_field("Package")
pkg_version <- get_field("Version")
pkg_title <- get_field("Title")

nixpkgs_url <- "https://github.com/rstats-on-nix/nixpkgs/archive/2025-12-22.tar.gz"

nix_content <- sprintf(
  paste(
    "# package.nix - Builds etfdata as a Nix derivation from local source",
    "# Generated by: R/setup/generate_nix_files.R",
    "",
    "{ pkgs ? import (fetchTarball \"%s\") {} }:",
    "",
    "pkgs.rPackages.buildRPackage rec {",
    "  name = \"%s\";",
    "  version = \"%s\";",
    "  src = ./.;",
    "",
    "  propagatedBuildInputs = with pkgs.rPackages; [",
    "%s",
    "  ];",
    "",
    "  nativeBuildInputs = with pkgs.rPackages; [",
    "%s",
    "  ];",
    "",
    "  doCheck = false;",
    "",
    "  meta = with pkgs.lib; {",
    "    description = \"%s\";",
    "    license = licenses.mit;",
    "  };",
    "}",
    "",
    sep = "\n"
  ),
  nixpkgs_url,
  escape_nix_string(pkg_name),
  escape_nix_string(pkg_version),
  format_nix_list(deps),
  format_nix_list(vignette_pkgs),
  escape_nix_string(pkg_title)
)

writeLines(nix_content, "package.nix")
message("Generated package.nix")
